Repository microPIECE-team/microPIECE, pull requests merged in 2018-03, with the labels that each got.

#81 Hotfix/piranha binsize
  README.md
  lib/microPIECE.pm
  microPIECE.pl
Labels: bug

#108 Account for single matures from mirbase 22
  scripts/MINING_complete_mirbase_by_miRDeep2_output.pl
Labels: bug, enhancement

#113 Add tests for piranha pre binning
  scripts/CLIP_binned_bed_from_bam_and_transcripts_for_piranha.pl
  scripts/CLIP_binned_bed_from_bam_for_piranha.pl
  scripts/CLIP_generate_transcript_bed_sorted_by_bed.pl
  t/CLIP_binned_bed_from_bam_and_transcripts_for_piranha.t
  t/testset_binning/README
  t/testset_binning/hs10_sim.bam
  t/testset_binning/hs10_sim.bam.bai
  t/testset_binning/simulation.tar.bz2
  t/testset_binning/tca_testset_small.gff
Labels: enhancement

#114 enhanced paper.bib with dois
  paper/paper.bib
Labels: enhancement

#122 changed docker version from master to tagged
  README.md
Labels: enhancement

#121 changed docker version from master to tagged
  README.md
Labels: enhancement

#126 Usage of miRNA.dat as input for mining
  README.md
  lib/microPIECE.pm
  microPIECE.pl
  scripts/MINING_complete_mirbase_by_miRDeep2_output.pl
  scripts/MINING_curate_mirdeep2fasta.pl
  scripts/lib/mining.pm
  t/MINING_complete_mirbase_by_miRDeep2_output.t
  t/MINING_curate_mirdeep2fasta.t
  t/hairpin_high_conf.fa
  t/mature_high_conf.fa
  t/miRNA_high_conf.dat
Labels: enhancement
